# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ProtoFile_pb2 as ProtoFile__pb2


class ClientMetricServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMetric = channel.unary_unary(
                '/ClientMetricService/SendMetric',
                request_serializer=ProtoFile__pb2.Metric.SerializeToString,
                response_deserializer=ProtoFile__pb2.Empty.FromString,
                )


class ClientMetricServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientMetricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMetric,
                    request_deserializer=ProtoFile__pb2.Metric.FromString,
                    response_serializer=ProtoFile__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClientMetricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientMetricService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientMetricService/SendMetric',
            ProtoFile__pb2.Metric.SerializeToString,
            ProtoFile__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
