# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoFile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fProtoFile.proto\"\"\n\x06Metric\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x02\x12\x0b\n\x03ram\x18\x02 \x01(\x02\"\x07\n\x05\x45mpty24\n\x13\x43lientMetricService\x12\x1d\n\nSendMetric\x12\x07.Metric\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoFile_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRIC._serialized_start=19
  _METRIC._serialized_end=53
  _EMPTY._serialized_start=55
  _EMPTY._serialized_end=62
  _CLIENTMETRICSERVICE._serialized_start=64
  _CLIENTMETRICSERVICE._serialized_end=116
# @@protoc_insertion_point(module_scope)
